name: GFD
favicon: null
layout_spectrum: 0.74969
typography_spectrum: 0.5
title: Glow Family Dental
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b5b5bd'
    - '#814c9e'
    - '#4c5fab'
    - '#9794c9'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
